"""Tests for Stage 6: IDS Alert Intelligence and RAG Alert Enrichment."""

import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

BACKEND_DIRECTORY = Path(__file__).resolve().parents[1] / "backend"
sys.path.insert(0, str(BACKEND_DIRECTORY))

from app.alerts.models import AlertSeverity, AlertStatus, Base
from app.alerts.schemas import AlertAnalysis, AlertEnrichmentResponse, AlertResponse
from app.database import get_db
from app.main import app
from app.rag.alert_enrichment import (
    ALERT_ANALYST_SYSTEM_PROMPT,
    FALLBACK_ENRICHMENT_SUMMARY,
    build_alert_analyst_prompt,
    build_alert_retrieval_query,
    enrich_alert,
    parse_analyst_response,
)
from app.rag.api import get_llm_provider
from app.rag.llm import GeminiProvider, LLMProvider
from app.rag.schemas import RAGSource


class MockAnalystLLM(LLMProvider):
    """Mock LLM that returns pre-configured JSON analysis."""

    def __init__(self, response_data: dict[str, Any] | str | None = None) -> None:
        if response_data is None:
            self.response_text = json.dumps({
                "summary": "PortScan alert indicates systematic probe against destination port 443.",
                "observed_indicators": [
                    "TCP SYN activity targeting port 443",
                    "High confidence model score (0.91)",
                ],
                "security_context": [
                    "MITRE ATT&CK T1046: Network Service Discovery",
                    "Adversaries scan ports to identify vulnerable listening services.",
                ],
                "investigation_steps": [
                    "Inspect firewall logs for packet bursts from source IP 192.0.2.10.",
                    "Verify if destination service responded with SYN-ACK or RST.",
                ],
                "recommended_mitigations": [
                    "Enforce rate-limiting on inbound perimeter interfaces.",
                    "Ensure unneeded exposed ports are closed.",
                ],
            })
        elif isinstance(response_data, dict):
            self.response_text = json.dumps(response_data)
        else:
            self.response_text = response_data

        self.calls: list[dict[str, Any]] = []

    def generate(self, prompt: str, system_instruction: str | None = None) -> str:
        self.calls.append({"prompt": prompt, "system_instruction": system_instruction})
        return self.response_text


def make_test_alert() -> dict[str, Any]:
    return {
        "id": uuid.uuid4(),
        "timestamp": datetime(2026, 9, 19, 10, 0, tzinfo=timezone.utc),
        "source_ip": "192.0.2.10",
        "destination_ip": "198.51.100.20",
        "source_port": 51515,
        "destination_port": 443,
        "protocol": "TCP",
        "attack_type": "PortScan",
        "confidence": 0.91,
        "severity": AlertSeverity.MEDIUM,
        "status": AlertStatus.NEW,
        "description": "Network-flow alert generated by trained IDS.",
        "created_at": datetime(2026, 9, 19, 10, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 9, 19, 10, 0, tzinfo=timezone.utc),
    }


def make_test_chunk(
    chunk_id: str = "chunk_t1046",
    score: float = 0.88,
    content: str = "Adversaries may attempt to get a listing of services running on remote hosts (T1046).",
    title: str = "Network Service Discovery",
) -> dict[str, Any]:
    return {
        "score": score,
        "document_id": "doc_ps",
        "chunk_id": chunk_id,
        "source": "mitre/parsed/techniques-attack-pattern--t1046.md",
        "file_name": "t1046.md",
        "file_type": "md",
        "content": content,
        "chunk_index": 1,
        "title": title,
        "metadata": {"relative_path": "mitre/parsed/t1046.md"},
    }


# ==========================================
# 1. Query & Prompt Construction Tests
# ==========================================

def test_build_alert_retrieval_query_multi_attribute() -> None:
    alert = make_test_alert()
    query = build_alert_retrieval_query(alert)

    assert "PortScan" in query
    assert "TCP" in query
    assert "destination port 443" in query
    assert "source port 51515" in query
    assert "detection investigation mitigation" in query


def test_build_alert_retrieval_query_handles_dict_and_object() -> None:
    alert_dict = {
        "attack_type": "DDoS",
        "protocol": "UDP",
        "destination_port": 53,
        "source_port": 41234,
    }
    query = build_alert_retrieval_query(alert_dict)
    assert "DDoS UDP destination port 53 source port 41234 detection investigation mitigation" == query


def test_analyst_prompt_construction_and_system_grounding() -> None:
    alert = make_test_alert()
    context = "Adversaries systematically probe ports to map services."
    prompt = build_alert_analyst_prompt(alert, context)

    # Verify alert details
    assert "PortScan" in prompt
    assert "198.51.100.20" in prompt
    assert "443" in prompt
    assert context in prompt

    # Verify strict system prompt rules
    assert "SOC analyst assistant" in ALERT_ANALYST_SYSTEM_PROMPT
    assert "Do not invent facts, attack attribution, indicators, incidents, or sources." in ALERT_ANALYST_SYSTEM_PROMPT
    assert "Do not claim that the alert proves a successful attack." in ALERT_ANALYST_SYSTEM_PROMPT
    assert "Do not invent MITRE technique IDs" in ALERT_ANALYST_SYSTEM_PROMPT


# ==========================================
# 2. Parsing & Malformed LLM Response Tests
# ==========================================

def test_parse_analyst_response_valid_json() -> None:
    alert = make_test_alert()
    raw = json.dumps({
        "summary": "Valid summary.",
        "observed_indicators": ["Ind 1"],
        "security_context": ["Ctx 1"],
        "investigation_steps": ["Step 1"],
        "recommended_mitigations": ["Mit 1"],
    })
    analysis = parse_analyst_response(raw, alert)

    assert analysis.summary == "Valid summary."
    assert analysis.observed_indicators == ["Ind 1"]
    assert analysis.security_context == ["Ctx 1"]
    assert analysis.investigation_steps == ["Step 1"]
    assert analysis.recommended_mitigations == ["Mit 1"]


def test_parse_analyst_response_handles_markdown_codeblock() -> None:
    alert = make_test_alert()
    raw = "```json\n" + json.dumps({
        "summary": "Codeblock summary.",
        "observed_indicators": ["Ind 2"],
    }) + "\n```"
    analysis = parse_analyst_response(raw, alert)

    assert analysis.summary == "Codeblock summary."
    assert analysis.observed_indicators == ["Ind 2"]


def test_parse_analyst_response_malformed_text_fallback() -> None:
    alert = make_test_alert()
    raw_text = "This is a plain text analyst note without JSON formatting. Port scan observed."
    analysis = parse_analyst_response(raw_text, alert)

    assert isinstance(analysis, AlertAnalysis)
    assert "plain text analyst note" in analysis.summary
    assert any("PortScan" in ind for ind in analysis.observed_indicators)
    assert len(analysis.investigation_steps) > 0


# ==========================================
# 3. Enrichment Function Unit Tests
# ==========================================

def test_enrich_alert_success_with_mocked_llm(monkeypatch: pytest.MonkeyPatch) -> None:
    test_chunk = make_test_chunk()
    monkeypatch.setattr("app.rag.alert_enrichment.search_chunks", lambda **kwargs: [test_chunk])

    mock_llm = MockAnalystLLM()
    alert = make_test_alert()

    analysis, sources = enrich_alert(alert, llm_client=mock_llm)

    assert "PortScan alert indicates systematic probe" in analysis.summary
    assert len(analysis.investigation_steps) == 2
    assert len(sources) == 1
    assert sources[0].chunk_id == "chunk_t1046"
    assert sources[0].score == pytest.approx(0.88)
    assert sources[0].title == "Network Service Discovery"

    # Verify LLM was called with strict system prompt
    assert len(mock_llm.calls) == 1
    assert mock_llm.calls[0]["system_instruction"] == ALERT_ANALYST_SYSTEM_PROMPT


def test_enrich_alert_empty_retrieval_returns_fallback(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr("app.rag.alert_enrichment.search_chunks", lambda **kwargs: [])
    mock_llm = MockAnalystLLM()
    alert = make_test_alert()

    analysis, sources = enrich_alert(alert, llm_client=mock_llm)

    assert analysis.summary == FALLBACK_ENRICHMENT_SUMMARY
    assert sources == []
    assert len(mock_llm.calls) == 0, "LLM must NOT be called when retrieval is empty"


def test_enrich_alert_missing_api_key_raises_runtime_error(monkeypatch: pytest.MonkeyPatch) -> None:
    test_chunk = make_test_chunk()
    monkeypatch.setattr("app.rag.alert_enrichment.search_chunks", lambda **kwargs: [test_chunk])
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)

    alert = make_test_alert()
    with pytest.raises(RuntimeError, match="GEMINI_API_KEY"):
        enrich_alert(alert, llm_client=GeminiProvider(api_key=None))


def test_enrich_alert_llm_failure_propagates_runtime_error(monkeypatch: pytest.MonkeyPatch) -> None:
    test_chunk = make_test_chunk()
    monkeypatch.setattr("app.rag.alert_enrichment.search_chunks", lambda **kwargs: [test_chunk])

    class FailingLLM(LLMProvider):
        def generate(self, prompt: str, system_instruction: str | None = None) -> str:
            raise RuntimeError("Gemini API connection timeout")

    alert = make_test_alert()
    with pytest.raises(RuntimeError, match="Gemini API connection timeout"):
        enrich_alert(alert, llm_client=FailingLLM())


# ==========================================
# 4. FastAPI Endpoint Integration Tests
# ==========================================

@pytest.fixture
def sqlite_client() -> TestClient:
    engine = create_engine("sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool)
    Base.metadata.create_all(engine)
    factory = sessionmaker(bind=engine)

    def override_db():
        with factory() as session:
            yield session

    app.dependency_overrides[get_db] = override_db
    with TestClient(app) as test_client:
        yield test_client
    app.dependency_overrides.clear()
    Base.metadata.drop_all(engine)


def test_api_enrich_alert_success(sqlite_client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    test_chunk = make_test_chunk()
    monkeypatch.setattr("app.rag.alert_enrichment.search_chunks", lambda **kwargs: [test_chunk])

    mock_llm = MockAnalystLLM()
    app.dependency_overrides[get_llm_provider] = lambda: mock_llm

    # Create alert in SQLite
    create_res = sqlite_client.post("/alerts", json={
        "timestamp": "2026-09-19T10:00:00Z",
        "source_ip": "192.0.2.10",
        "destination_ip": "198.51.100.20",
        "source_port": 51515,
        "destination_port": 443,
        "protocol": "TCP",
        "attack_type": "PortScan",
        "confidence": 0.91,
        "severity": "Medium",
        "description": "Network alert for testing enrichment.",
    })
    assert create_res.status_code == 201
    alert_id = create_res.json()["id"]

    # Call POST /alerts/{alert_id}/enrich
    enrich_res = sqlite_client.post(f"/alerts/{alert_id}/enrich")
    assert enrich_res.status_code == 200

    data = enrich_res.json()
    assert data["alert"]["id"] == alert_id
    assert data["alert"]["attack_type"] == "PortScan"
    assert "PortScan alert indicates systematic probe" in data["analysis"]["summary"]
    assert len(data["sources"]) == 1
    assert data["sources"][0]["chunk_id"] == "chunk_t1046"
    assert data["sources"][0]["score"] == pytest.approx(0.88)


def test_api_enrich_alert_not_found_404(sqlite_client: TestClient) -> None:
    random_id = str(uuid.uuid4())
    res = sqlite_client.post(f"/alerts/{random_id}/enrich")
    assert res.status_code == 404
    assert res.json()["detail"] == "Alert not found."


def test_api_enrich_alert_missing_api_key_returns_503(sqlite_client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    test_chunk = make_test_chunk()
    monkeypatch.setattr("app.rag.alert_enrichment.search_chunks", lambda **kwargs: [test_chunk])
    monkeypatch.delenv("GEMINI_API_KEY", raising=False)

    # Create alert
    create_res = sqlite_client.post("/alerts", json={
        "timestamp": "2026-09-19T10:00:00Z",
        "source_ip": "192.0.2.10",
        "destination_ip": "198.51.100.20",
        "source_port": 51515,
        "destination_port": 443,
        "protocol": "TCP",
        "attack_type": "PortScan",
        "confidence": 0.91,
        "severity": "Medium",
        "description": "Test alert for 503 check.",
    })
    alert_id = create_res.json()["id"]

    # Use real GeminiProvider without key
    app.dependency_overrides[get_llm_provider] = lambda: GeminiProvider(api_key=None)

    enrich_res = sqlite_client.post(f"/alerts/{alert_id}/enrich")
    assert enrich_res.status_code == 503
    assert "GEMINI_API_KEY" in enrich_res.json()["detail"]
